import styles from '../styles/Home.module.css'
import { useEffect, useState, useContext } from 'react';
import { SessionContext } from "../context";
import Head from 'next/head'
import Link from 'next/link';
 
import styled from '@emotion/styled'; 
import Layout from '../layouts'
import { Button, Container, Typography } from '@mui/material';

 const StyledContainer = styled(Container)`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  margin:0.888rem auto;
  width: 444px;
  max-width: 444px;
  word-wrap: break-word;
  color: var(--blue-color-9);
  font-family: 'Roboto', sans-serif;
  font-size: 1.5rem;
  font-weight: 500;
  text-align: center;
`;
 

const otherPage = () => {
const { session,  account } = useContext(SessionContext);
const [accountDetails, setAccountDetails] = useState<any>(null)
    useEffect(() => {
        if (session) {
            setAccountDetails(account)
        }
        return () => {
            setAccountDetails(null)
          }
    }, [session])
    return (
        <Container className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main id="app" className={styles.main}>
                <h1 className={styles.title} style={{ marginBottom: '40px' }}>
                    Welcome to the <a href="#!">Other Page</a>
                </h1>
 
                <StyledContainer>
          <Typography variant="h4" component="span" gutterBottom >
            {accountDetails ? `Hi, ${accountDetails?.actor}!` : 'Please login to continue'}
          </Typography>
        </StyledContainer>
   
        <Button variant="outlined" sx={{mt:4}}> 
        <Link href="/">Back to Home</Link>
        </Button>
        
            </main>
        </Container>
    )
}


otherPage.getLayout = function getLayout(page: any) {
    return <Layout simpleFooter simpleHeader>{page}</Layout>;
  };
  
  export default otherPage